-- AvancePR schema — mirrors the Django models it replaces (advancepr_backend/main/models.py)
-- column-for-column, so existing Postgres data can be moved over later with a plain
-- pg_dump/COPY into these tables (same table + column names as Django's `main_*`).
--
-- Run once in the Supabase project: SQL Editor -> paste this file -> Run.
--
-- Access model: RLS is enabled on every table with NO policies, so only requests
-- using the `service_role` key (server-side only, e.g. Next.js API routes /
-- getStaticProps) can read or write. The anon/public key gets nothing. The `media`
-- storage bucket is public-read so uploaded images can be served directly.

-- ---------------------------------------------------------------------------
-- shared trigger: keep updated_at current on every UPDATE
-- ---------------------------------------------------------------------------
create or replace function set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- ---------------------------------------------------------------------------
-- main_testimonial
-- ---------------------------------------------------------------------------
create table main_testimonial (
  id bigint generated by default as identity primary key,
  "order" integer not null default 0 check ("order" >= 0),
  name varchar(50) not null,
  designation varchar(50) not null,
  content text not null,
  image varchar(100),
  is_archived boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger trg_main_testimonial_updated_at
  before update on main_testimonial
  for each row execute function set_updated_at();

alter table main_testimonial enable row level security;

-- ---------------------------------------------------------------------------
-- main_ourclient
-- ---------------------------------------------------------------------------
create table main_ourclient (
  id bigint generated by default as identity primary key,
  "order" integer not null default 0 check ("order" >= 0),
  image varchar(100),
  name varchar(100) not null default 'Unnamed Client',
  is_archived boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger trg_main_ourclient_updated_at
  before update on main_ourclient
  for each row execute function set_updated_at();

alter table main_ourclient enable row level security;

-- ---------------------------------------------------------------------------
-- main_ourwork
-- ---------------------------------------------------------------------------
create table main_ourwork (
  id bigint generated by default as identity primary key,
  "order" integer not null default 0 check ("order" >= 0),
  content varchar(50) not null,
  image varchar(100),
  banner varchar(100),
  description text,
  is_archived boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger trg_main_ourwork_updated_at
  before update on main_ourwork
  for each row execute function set_updated_at();

alter table main_ourwork enable row level security;

-- ---------------------------------------------------------------------------
-- main_latestnews
-- ---------------------------------------------------------------------------
create table main_latestnews (
  id bigint generated by default as identity primary key,
  "order" integer not null default 0 check ("order" >= 0),
  content text not null,
  image varchar(100),
  link varchar(200),
  is_archived boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger trg_main_latestnews_updated_at
  before update on main_latestnews
  for each row execute function set_updated_at();

alter table main_latestnews enable row level security;

-- ---------------------------------------------------------------------------
-- main_awardsrecognition
-- ---------------------------------------------------------------------------
create table main_awardsrecognition (
  id bigint generated by default as identity primary key,
  "order" integer not null default 0 check ("order" >= 0),
  content text not null,
  image varchar(100),
  link varchar(200),
  is_archived boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger trg_main_awardsrecognition_updated_at
  before update on main_awardsrecognition
  for each row execute function set_updated_at();

alter table main_awardsrecognition enable row level security;

-- ---------------------------------------------------------------------------
-- main_blog
-- ---------------------------------------------------------------------------
create table main_blog (
  id bigint generated by default as identity primary key,
  "order" integer not null default 0 check ("order" >= 0),
  author varchar(50) not null,
  title varchar(100) not null,
  body text,
  body_md text,
  image varchar(100),
  credits text,
  is_archived boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger trg_main_blog_updated_at
  before update on main_blog
  for each row execute function set_updated_at();

alter table main_blog enable row level security;

-- ---------------------------------------------------------------------------
-- main_enquiry
-- ---------------------------------------------------------------------------
create table main_enquiry (
  id bigint generated by default as identity primary key,
  full_name varchar(100) not null,
  email varchar(254) not null,
  phone varchar(20) not null,
  company_name varchar(50),
  enquiry text not null default '',
  is_archived boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger trg_main_enquiry_updated_at
  before update on main_enquiry
  for each row execute function set_updated_at();

alter table main_enquiry enable row level security;

-- ---------------------------------------------------------------------------
-- storage bucket for new image uploads (existing images stay on Azure Blob)
-- ---------------------------------------------------------------------------
insert into storage.buckets (id, name, public)
values ('media', 'media', true)
on conflict (id) do nothing;

create policy "media bucket is publicly readable"
  on storage.objects for select
  using (bucket_id = 'media');
